dbt_novel:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qf87116.eu-central-1

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: novel
      warehouse: xsmall_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False